version: '2'
services:
    homedical-app:
        image: homedical
        container_name: homedical-app
        volumes:
            - /home/esparta/homedical/logs:/home/esparta/homedical/logs
            - /etc/letsencrypt:/etc/letsencrypt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SERVER_PORT=8080
            - LOGGING_PATH=/home/esparta/homedical/logs
            - SPRING_DATASOURCE_URL=jdbc:mysql://homedical-mysql:3306/homedical?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false
            - SPRING_DATASOURCE_USERNAME=homedical
            - SPRING_DATASOURCE_PASSWORD=password
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 127.0.0.1:8080:8080
    homedical-mysql:
        extends:
            file: mysql.yml
            service: homedical-mysql
