version: '2'
services:
    homedical-mysql:
        image: mysql:5.7.18
        # volumes:
        #     - ~/volumes/jhipster/homedical/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=homedical
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_DATABASE=homedical
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
